### ISSUE TITLE
ValueError: The value for a TraceParameter cannot be empty

### ISSUE THREAD

**Issue by nsygtc** [Riscure/python-trsfile#13]

**Comment by nsygtc** [comment]
<img width="1011" alt="c7689a2b1d92017c1df591bf540952e" src="https://user-images.githubusercontent.com/68743327/130036421-29cf1ed6-5fbe-46cd-9aca-0d5e13da6c04.png">

**Comment by TomHogervorst** [comment]
Which operating system and version of python are you using? The behavior of os.urandom depends on both. 
You could check whether `os.urandom(16)` is producing a non-empty array of values, and if it is, choose a different method of producing a byte array.

**Comment by nsygtc** [comment]
> Which operating system and version of python are you using? The behavior of os.urandom depends on both.
> You could check whether `os.urandom(16)` is producing an empty array of values, and if it is, choose a different method of producing a byte array.

Thank you very much! My error caused by adding extra attributes of header. Now it solved!
