### ISSUE TITLE
Inspector 2020.1

### ISSUE THREAD

**Issue by jogolden** [Riscure/python-trsfile#4]
I generated a trace file using this...
```py
traces = trsfile.trs_open("traces.trs", "w", padding_mode=trsfile.TracePadding.AUTO)
traces.append(trsfile.Trace(trsfile.SampleCoding.BYTE, tracedata, data=plaintext))
```

When I load this trace file in Inspector, I get the following error...
```
WARNING: wrong length trace block (17506800)
Exception reading tag: HE (74): illegal length of int object (114)
Exception reading tag: ET (61): illegal length of float object (99)
```

You may download the traces here [traces.zip](https://github.com/Riscure/python-trsfile/files/4905615/traces.zip)

**Comment by johan-riscure** [comment]
I can open the trace set file you attached just fine (no warnings) with Inspector 2020.1, as well as with Inspector FI Python. Could you check if others have this problem as well? It may be something system specific (perhaps related to character encoding).

Just to check: did you open the file in Inspector while you were generating it?

**Comment by StefanD986** [comment]
@jogolden I can also open the traceset. Can you
  - paste your Help => About version info
  - open a CMD and paste output of `chcp`
  - open `C:\Program Files\Inspector-2020.1-sca-fi\jdk64\bin\jshell.exe` and run and paste the output of
```java
import java.nio.charset.Charset;
Charset.defaultCharset()
```

**Comment by jogolden** [comment]
```
|  Welcome to JShell -- Version 11.0.5
|  For an introduction type: /help intro

jshell> import java.nio.charset.Charset;

jshell> Charset.defaultCharset()
$2 ==> windows-1252

jshell>
```

I re-downloaded the traces and tried opening it again. This time it worked but the data was all messed up for some reason. Almost like it was truncated. I then tried using SampleCoding.FLOAT and it was fine.
