### ISSUE TITLE
open(filename,'a') error

### ISSUE THREAD

**Issue by ghostor1d** [Riscure/python-trsfile#6]
```
if self.read_headers and headers is not None:
	raise TypeError('Cannot change headers when reading TRS files.')
elif not self.read_headers and headers is not None and any(not isinstance(header, Header) for header in headers):
	raise TypeError('Creation of TRS files requires passing instances of Headers to the constructor.')
```
I try append traces in a existed normal trsfile.
if open existed trsfile, headers must is not None.

**Comment by johan-riscure** [comment]
You'll have to provide a bit more details on what you did exactly and what error you get (you're just quoting the source code now) for us to be able to help you

**Comment by nsygtc** [comment]
hi, I can't create a .trs file according to your README - Creating .trs files. Specifically, Pycharm shows "ValueError: The value for a TraceParameter cannot be empty".   What should I do? Thank you!
<img width="1011" alt="c7689a2b1d92017c1df591bf540952e" src="https://user-images.githubusercontent.com/68743327/130035230-559ead5b-c48c-459f-9144-c6d7205048d4.png">
